import {
    movie,
    face,
    house,
    car,
    gammaImage,
    uber,
    book,
    bank,
    puzzle8,
    barcelona,
    galytna,
    connect4,
    suddoku
} from "../assets/images";
import {
    contact,
    github,
    linkedin,
    // new icons
    java,
    sql,
    python,
    c,
    powerbi,
    react,
    tailwindcss,
    nodejs,
    upwork,
    khamsat_1,
    anu,
    nti,
    depi,
    island,
    mostaql, // ✅ import Mostaql icon
} from "../assets/icons";

// ====================== Skills ======================
export const skills = [
    { imageUrl: python, name: "Python", type: "Programming Language" },
    { imageUrl: sql, name: "SQL", type: "Database" },
    { imageUrl: java, name: "Java", type: "Programming Language" },
    { imageUrl: c, name: "C", type: "Programming Language" },
    { imageUrl: react, name: "React", type: "Frontend" },
    { imageUrl: tailwindcss, name: "TailwindCSS", type: "Frontend" },
    { imageUrl: nodejs, name: "Node.js", type: "Backend" },
    { imageUrl: powerbi, name: "Power BI", type: "Data Visualization" },
];

// ====================== Experiences / Timeline ======================
export const experiences = [{
    title: "Expected Graduation",
    company_name: "Alexandria National University",
    iconBg: "#a2d2ff",
    date: "2027",
    icon: anu,
    points: ["B.Sc. in Computer and Communications Engineering."],
},
{
    title: "Machine Learning for Data Analysis",
    company_name: "NTI",
    iconBg: "#f0c987",
    date: "2025",
    icon: nti,
    points: [
        "Learned ML concepts and applied them to real datasets.",
        "Built predictive models and data pipelines.",
    ],
},
{
    title: "Data Analysis with Power BI",
    company_name: "Ro2ad Masr Digital Initiative",
    iconBg: "#fbc3bc",
    date: "2025",
    icon: depi,
    points: [
        "Learned Power BI, DAX, and Excel.",
        "Built real-world dashboards.",
    ],
},
{
    title: "Developed Ashraf Game",
    company_name: "Personal Project",
    iconBg: "#b7e4c7",
    date: "2023",
    icon: island,
    points: ["Created a 3D interactive game with React + Three.js."],
},
];

// ====================== Social Links ======================
export const socialLinks = [
    { name: "Contact", iconUrl: contact, link: "/contact" },
    {
        name: "GitHub",
        iconUrl: github,
        link: "https://github.com/MohamedAshraf-DE",
    },
    {
        name: "LinkedIn",
        iconUrl: linkedin,
        link: "https://www.linkedin.com/in/mohamed--ashraff",
    },

    // ✅ Freelance platforms grouped together
    {
        name: "Upwork",
        iconUrl: upwork,
        link: "https://www.upwork.com/freelancers/~0190a07e5b17474f9f?mp_source=share",
    },
    {
        name: "Khamsat",
        iconUrl: khamsat_1,
        link: "https://khamsat.com/user/mohamed_ashraf124",
    },
    {
        name: "Mostaql",
        iconUrl: mostaql,
        link: "https://mostaql.com/u/MohamedA_Data",
    },
];

// ====================== Projects ======================
export const projects = [
    {
        iconUrl: java,
        imageUrl: bank,
        theme: "btn-back-red",
        name: "Banking System",
        description: "A Java-based banking management system implementing core OOP principles for handling accounts and transactions.",
        link: "",
        category: "Software Dev",
    },
    {
        iconUrl: powerbi,
        imageUrl: uber,
        theme: "btn-back-green",
        name: "Uber Dashboard",
        description: "A data analytics dashboard built with Power BI to analyze Uber ride data and extract customer and driver insights.",
        link: "",
        category: "Data Visualization",
    },
    {
        iconUrl: python,
        imageUrl: car,
        theme: "btn-back-blue",
        name: "Uber Ride Cancellation Prediction",
        description: "A machine learning model to predict Uber ride cancellations using Python and real-world datasets.",
        link: "https://uber-ride-cancellation-prediction-xkvtpafyqcn47jzkucb9y2.streamlit.app/",
        category: "Machine Learning",
    },
    {
        iconUrl: python,
        imageUrl: face,
        theme: "btn-back-orange",
        name: "Face Recognition System",
        description: "A real-time face recognition application deployed on Streamlit.",
        link: "https://face-recognition-ewkfhzievscgxqtozamxbh.streamlit.app/",
        category: "Computer Vision",
    },
    {
        iconUrl: python,
        imageUrl: house,
        theme: "btn-back-green",
        name: "California House Price Prediction",
        description: "Predicting housing prices in California using regression techniques.",
        link: "https://california-house-price-prediction-7elqhkbprshnxmrgewm3br.streamlit.app/",
        category: "Machine Learning",
    },
    {
        iconUrl: python,
        imageUrl: gammaImage,
        theme: "btn-back-red",
        name: "Gamma-Ray vs Hadron Classification",
        description: "Classifying Gamma-Ray and Hadron particles using machine learning algorithms.",
        link: "https://gamma-hadron-wt3lqfj46bw9h5yg43ar5n.streamlit.app/",
        category: "Machine Learning",
    },
    {
        iconUrl: python,
        imageUrl: movie,
        theme: "btn-back-black",
        name: "Movie Revenue Prediction",
        description: "A system to predict movie revenue based on various features.",
        link: "https://movie-revenue-prediction-jg37k7hrowdn7twnkatw3d.streamlit.app/",
        category: "Machine Learning",
    },
    {
        iconUrl: sql,
        imageUrl: book,
        theme: "btn-back-pink",
        name: "Online Book Store Database",
        description: "A comprehensive database design and implementation for an online book store.",
        link: "https://github.com/MohamedAshraf-DE/Online-Book-store",
        category: "Database Design",
    },
    {
        iconUrl: react,
        imageUrl: puzzle8,
        theme: "btn-back-blue",
        name: "8-Puzzle Game AI",
        description: "A fast, modern 8-puzzle game web application featuring smooth animations and an embedded AI agent to autonomously compute and play out the optimal puzzle solution.",
        link: "https://lnkd.in/dH7ugQzW",
        githubLink: "https://github.com/MohamedAshraf-DE/8-puzzle",
        category: "Artificial Intelligence",
    },
    {
        iconUrl: python,
        imageUrl: barcelona,
        theme: "btn-back-blue",
        name: "Barcelona",
        description: "A modern football scouting and analytics application designed to evaluate player profiles and support data-driven recruitment aligned with FC Barcelona's tactical philosophy.",
        link: "https://barcelona-khxuzfnpdfem5tjwgikxpu.streamlit.app/",
        githubLink: "https://github.com/MohamedAshraf-DE/Barcelona",
        category: "Sports Analytics",
    },
    {
        iconUrl: nodejs,
        imageUrl: galytna,
        theme: "btn-back-green",
        name: "جاليتنا",
        description: "A comprehensive community web platform providing services, cultural events, a community directory, news, and administrative management for the Lebanese Arab community.",
        link: "https://mohamedashraf-de.github.io/Lebanese-Arab-community/",
        githubLink: "https://github.com/MohamedAshraf-DE/Lebanese-Arab-community",
        category: "Full Stack Dev",
    },
    {
        iconUrl: python,
        imageUrl: connect4,
        theme: "btn-back-yellow",
        name: "Connect4",
        description: "An interactive Connect4 strategy game featuring an intelligent AI solver based on the Minimax algorithm.",
        link: "https://connect4-bcskedlcjd8plxwbvvpgkk.streamlit.app/",
        githubLink: "https://github.com/MohamedAshraf-DE/Connect4",
        category: "Artificial Intelligence",
    },
    {
        iconUrl: python,
        imageUrl: suddoku,
        theme: "btn-back-pink",
        name: "Suddoku",
        description: "An interactive Sudoku game and automatic puzzle solver powered by constraint satisfaction and backtracking algorithms.",
        link: "https://sudokou-o9xb4j3jxrywpkxqpmd4pq.streamlit.app/",
        githubLink: "https://github.com/MohamedAshraf-DE/Sudokou",
        category: "Artificial Intelligence",
    },
];